### PR TITLE
API and Angular Routing fixes

### LINKED ISSUE #46: "Not found" specification returns HTTP 500 instead of 404
```
$ curl http://localhost:8080/specifications/65039ab5-b610-4038-9afb-98b45f7fe9fc
{"id":"65039ab5-b610-4038-9afb-98b45f7fe9fc", ... }

$ curl http://localhost:8080/specifications/65039ab5-b610-4038-9afb-98b45f7fe9fd
{"timestamp":1549027851225,"status":500,"error":"Internal Server Error","message":"No value present","path":"/specifications/65039ab5-b610-4038-9afb-98b45f7fe9fd"}
```

### LINKED ISSUE #47: Add a 404 page to the web app
Currently a GET for a non-existent specification in the webapp produces only toolbar + white page, with no indication of what has gone wrong.

blank

### PR DESCRIPTION
**Pull request by catenoid**
Two related changes here to do with the API

## API redefinition
Firstly, modifies Spring config to route all HTTP requests to Angular. Before, every route within Angular's SPA had to be accessed from the root; if the user refreshed the page or sent a static link to someone, Spring would return 404.

Secondly, because both API path requests and Angular routes are now in the same scope / namespace, adds a prefix to all API calls, to distinguish the two services. Updates integration tests. (Also removes '/versions/' from API calls, to make the API vs Angular paths consistent.)

## Add handling for unfound versions / specifications

Before, the findOne methods assumed every request for a version / specification would succeed. When the user gave a non-existent specification ID, the server threw an exception, and 500 was returned to the client.

Now curl requests for non-existent IDs return 404 (fix #46), and in the web frontend, an error banner appears instead of the whole page being blank (fix #47)

### CODE REVIEW

File: backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerIntegrationTest.kt [hunk 1]
```diff
@@ -28,7 +28,7 @@ internal class SpecificationControllerIntegrationTest {
 
     @Test
     fun findAllSpecifications_shouldReturnAllSpecifications() {
-        mockMvc.perform(get("/specifications").with(user("user")))
+        mockMvc.perform(get("/api/1.0/specifications").with(user("user")))
```
Comment (fdw) [inline backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerIntegrationTest.kt]: Minor version numbers in the API are really unusual. I would rather not use it. Instead something like "v1" so that you can easily see what the number is meant to signify.

File: backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerIntegrationTest.kt [hunk 2]
```diff
@@ -41,10 +41,30 @@ internal class SpecificationControllerIntegrationTest {
             .andExpect(jsonPath("$[2].versions[1].version", equalTo("1.1")))
     }
 
+    @Test
+    fun findAllSpecifications_requiresAuthentication() {
+        mockMvc.perform(get("/api/1.0/specifications"))
+                .andExpect(status().`is`(403))
```
Comment (fdw) [inline backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerIntegrationTest.kt]: There's also `isForbidden()` and so on, which might be easier to read.

File: backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt [hunk 3]
```diff
@@ -25,15 +25,24 @@ class VersionControllerIntegrationTest {
 
     @Test
     fun findOneVersion_shouldReturnVersion() {
-        mockMvc.perform(get("/specifications/b6b06513-d259-4faf-b34b-a216b3daad6a/versions/v1")
+        mockMvc.perform(get("/api/1.0/specifications/b6b06513-d259-4faf-b34b-a216b3daad6a/v1")
```
Comment (fdw) [inline backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt]: I think I'd rather keep the `/versions/` bit, so that you can get a list of all versions from there.

File: backend/src/main/kotlin/com/tngtech/apicenter/backend/config/SecurityConfiguration.kt [hunk 4]
```diff
@@ -21,22 +21,27 @@ class SecurityConfiguration : WebSecurityConfigurerAdapter() {
...
-            .antMatchers("/open-iconic.*").permitAll()
-            .anyRequest().authenticated()
-            .and()
-            .addFilter(JwtAuthorizationFilter(authenticationManager(), jwtSecuritySecret))
-            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
+                .cors()
+                .and()
+                .csrf().disable()
+                .authorizeRequests()
+                .antMatchers("/api/1.0/sessions").permitAll()
```
Comment (fdw) [inline backend/src/main/kotlin/com/tngtech/apicenter/backend/config/SecurityConfiguration.kt]: There's lots of different matchers. Do we really want the `Ant` ones, or is there something better?

File: backend/src/main/kotlin/com/tngtech/apicenter/backend/config/WebConfiguration.kt [hunk 5]
```diff
@@ -15,6 +16,18 @@ class WebConfiguration {
                 corsRegistry.addMapping("/**").allowedOrigins("*").allowedMethods("*")
                     .allowedHeaders("*")
             }
+
+            override fun addViewControllers(registry: ViewControllerRegistry) {
+                // Redirect to Angular's router
+                // In case you either refresh the page, or want to send a static link to someone
```
Comment (fdw) [inline backend/src/main/kotlin/com/tngtech/apicenter/backend/config/WebConfiguration.kt]: I think the first line of the comment is sufficient

File: backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt [hunk 6]
```diff
@@ -57,8 +57,15 @@ class SpecificationController @Autowired constructor(
         specificationHandler.findAll().map { spec -> specificationDtoMapper.fromDomain(spec) }
 
     @GetMapping("/{specificationId}")
-    fun findSpecification(@PathVariable specificationId: UUID): SpecificationDto =
-        specificationDtoMapper.fromDomain(specificationHandler.findOne(specificationId)!!)
+    @Throws(HttpNotFoundException::class)
+    fun findSpecification(@PathVariable specificationId: UUID): SpecificationDto {
+        val specification = specificationHandler.findOne(specificationId)
+
+        if (specification != null) {
```
Comment (fdw) [inline backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt]: I think you can do something like
```
specification.?let { specificationDtoMapper.fromDomain(it) } ?: throw HttpNotFoundException()
```

File: backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt (hunk 3 above)
Comment (catenoid) [reply backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt]: Sorry I don't understand. How does `/versions/` add meaning? The resource path is uniquely identifiable by the specID and version alone. I don't mind changing it, but would like to know why

File: backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt (hunk 6 above)
Comment (catenoid) [reply backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt]: Awesome 😄 Much neater

File: backend/src/main/kotlin/com/tngtech/apicenter/backend/config/SecurityConfiguration.kt (hunk 4 above)
Comment (catenoid) [reply backend/src/main/kotlin/com/tngtech/apicenter/backend/config/SecurityConfiguration.kt]: I was deliberately overcautious here, because (afaiu) the Ant matchers match resources from a number of different roots: `/resources`, `/resources/public`, and the HTTP routes. If you're more liberal with the permitted routes, you can access the properties files, for example.

File: backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt (hunk 3 above)
Comment (fdw) [reply backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt]: While I agree that it looks unnecessary, I think I only ever saw REST interfaces with the "parameter-names" added. For example, if I make a GET call to `/specifications/{id}`, I get that resource. If I would make one to `/specifications/{id}/versions` I'd expect to get a list of all the versions. If we don't have the `versions` part anymore, where do I get this list?

Comment (catenoid) [reply backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt]: `/specifications/{specificationId}/versions` was never an API endpoint. (I had not made any edits to api-definition.json until now.) 😕

Comment (fdw) [reply backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt]: Doesn't have to be right now, but at least we have the opportunity.
